### ISSUE TITLE
Touch Controller build issue

### ISSUE THREAD

**Issue by VRtinker** [CidVonHighwind/VirtualBoyGo#9]
Hi,

After jumping a series of hoops, I managed to compile the code successfully and test it on the Quest. There are three issues (at least) that are not present in the last official version.

The "Start" button of the left touch controller consistently crashes the app if pressed on first load, before trying to load any rom.

The framerate is severely reduced compared to the previous builds; this has also a negative effect on the audio output. It's generally laggy all-around, including the input from the buttons.

When exiting, whether you do so by navigating the app menu and selecting exit, or using the right touch controller oculus platform button, the app will not exit gracefully, and the system report it.

Hopefully it will be possible to eliminate this bug!

Finger crossed

**Comment by CidVonHighwind** [comment]
Thank you for the testing. I do not own a Quest and can not test this stuff myself so I am thankful for people like you.
I will try to fix all the bugs before releasing a new build. For the frame-rate issue try to build the app with the release build variant instead of the debug on. (Build/Edit Build Types...)

**Comment by CidVonHighwind** [comment]
The two issues should now be fixed and I will probably release the current version after testing it more.
